#!/bin/bash

cat << "EOF"
 __        __   _                           
 \ \      / /__| | ___ ___  _ __ ___   ___  
  \ \ /\ / / _ \ |/ __/ _ \| '_ ` _ \ / _ \ 
   \ V  V /  __/ | (_| (_) | | | | | |  __/ 
  _ \_/\_/ \___|_|\___\___/|_| |_| |_|\___| 
 | |_ ___   |_ _| | |_   _ _ __ ___   ___   
 | __/ _ \   | || | | | | | '_ ` _ \ / _ \  
 | || (_) |  | || | | |_| | | | | | |  __/  
  \__\___/  |___|_|_|\__,_|_| |_| |_|\___|  
                                            

Please visit the user guide here for information:
https://sites.google.com/ualberta.ca/illume/home

If you have any issues or requests, please contact:
Jamie Rajewski <jrajewsk@ualberta.ca>

EOF
